In [1]:
get_ipython().run_cell_magic('capture', '', "%logstop\n%logstart -t -r -q ipython_command_log.py global\n\n#- IRONHACKS RESEARCH TRACKING CODE\n#----------------------------------\n# The following code is used to help our research team understand how you \n# our notebook environment. We do not collect any personal information with\n# the following code, it is used to measure when and how often you work on\n# your submission files.\n\nimport os\nfrom datetime import datetime\nimport IPython.core.history as history\n\nha = history.HistoryAccessor()\nha_tail = ha.get_tail(1)\nha_cmd = next(ha_tail)\nsession_id = str(ha_cmd[0])\ncommand_id = str(ha_cmd[1])\ntimestamp = datetime.utcnow().isoformat()\nhistory_line = ','.join([session_id, command_id, timestamp]) + '\\n'\nlogfile = open(os.environ['HOME']+'/ipython_session_log.csv', 'a')\nlogfile.write(history_line)\nlogfile.close()\n")

SUBMISSION 11 Milestone
The task was to predict the total_claims for week 42
For each week there is a distinct list of uu_ids with unique uu_id in the table called prediction_list
Predict a value for each of those uu_ids
The list is changing over time (given the streaming nature of the data)

In [2]:
get_ipython().run_cell_magic('capture', '', "\n# INSTALL ADDITIONAL LIBRARIES IF REQUIRED\n# ------------------------------------------\n# This is normally not required. The hub environment comes preinstaled with \n# many packages that you can already use without setup. In case there is some\n# other library you would like to use that isn't on the list you run this command\n# once to install them.  If it is already installed this command has no effect.\n\n!python3 -m pip install pandas\n!python3 -m pip install [ensorflow]\n!python3 -m pip install [Keras]\n!python3 -m pip install [Pytorch]\n")

INSTALL PACKAGES

In [3]:
get_ipython().system('pip install db-dtypes')

IMPORT THE LIBRARIES YOU WILL USE
------------------------------------------
You only need to import packages one time per notebook session. To keep your
notebook clean and organized you can handle all imports at the top of your file.
The following are included for example purposed, feel free to modify or delete 
anything in this section.

In [4]:
import csv
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics
import statsmodels.api as sm
import math

IMPORT THE DATASET

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')

In [6]:
import os
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

IMPORT IRONHACKS DATA

In [7]:
import os
BIGQUERY_PROJECT = 'ironhacks-data'

In [8]:
bigquery.Client(project=BIGQUERY_PROJECT)

IMPORT THE LINEAR REGRESSION MODEL

In [9]:
import csv
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import matplotlib.pyplot as plt  

IMPORT PACKAGE THE LINEAR REGRESSION MODEL- SCIKIT-LEARN 
SOURCE: https://realpython.com/linear-regression-in-python/#simple-linear-regression-with-scikit-learn
NUMPY IS A FUNDAMENTAL PUYTHON SCIENTIFIC PACKAGE THAT ALLOWS MANY HIGH PEROFORMATION OPERATION SON A SINGLE AND MULTI DIMENSIONAL ARRAYS.
SOURCE: https://realpython.com/linear-regression-in-python/#python-packages-for-linear-regression

In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [11]:
# DEFINING THE DATA; INPUTS (REGRESSOR.X) AND OUTPUTS (RESPONSE.Y)
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

DEFINE YOUR CLASSES AND FUNCTIONS 
-----------------------------------
This is not required, but is helpful in keeping your notebook organized. 
You can use the following cell or several cells to define your functions
and classes to keep them separate from your analysis or results code.
In general it useful to define your methods in a separate cell from where
it is run.

In [12]:
def example_function():
    print('Hello World')

In [13]:
# CREATE A LINEAR REGRESSION MODEL
model = LinearRegression()

START USING A MODEL - .fit() fits the model
SOURCE: REAL PYTHON - https://realpython.com/linear-regression-in-python/#simple-linear-regression-with-scikit-learn

In [14]:
model.fit(x,y)
LinearRegression

sklearn.linear_model._base.LinearRegression

In [15]:
# GET RESULTS - NOW THAT THE MODEL HAS BEEN FITTED; LET SEE IF IT WORKS!
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


THE RETURN VALUE SHOULD BE R2

DETERMIINE HOW TO GET b0 and b1 (scikit-learn)
intercept and coefficient are estimated values

In [16]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [17]:
# DETERMIINE HOW TO GET b0 and b1 (scikit-learn)
# intercept and coefficient are estimated values
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [18]:
# NOW THAT WE KNOW OUR MODEL IS WORKING; LET'S PREDICT A RESPONSE!
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


HERE'S ANOTHER WAY TO PREDICT THE RESPONSE
THIS IS WERE EACH ELEMENT OF X WERE MULTIPLIED BY WITH THE MODEL COEFFICIENT

In [19]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


REGRESSION MODELS ARE TYPCIALLY USED FOR FORECASTS
FITTED MODELS CAN BE USED TO CALCULATE THE OUTPUTS

In [20]:
x_new = np.arange(5). reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
# REGRESSION MODELS ARE TYPCIALLY USED FOR FORECASTS
# FITTED MODELS CAN BE USED TO CALCULATE THE OUTPUTS
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

Obtain data using BigQuery

In [22]:
BIGQUERY_PROJECT = 'ironhacks-data'
bigquery_client = bigquery.Client(project=BIGQUERY_PROJECT)

In [23]:
query = """
SELECT
x.*,
y.average_wage
FROM
(SELECT
*
FROM `ironhacks-data.ironhacks_competition.unemployment_data`) x
JOIN `ironhacks-data.ironhacks_competition.wage_data` y
ON x.uu_id = y.uu_id
"""

In [24]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()

In [25]:
query_pred = """
SELECT * FROM `ironhacks-data.ironhacks_competition.prediction_list`
"""

In [26]:
query_job_pred = bigquery_client.query(query_pred)
data_pred_query= query_job_pred.to_dataframe()

In [27]:
# START USING A MODEL - Same statement written differently
model = LinearRegression().fit(x,y)

In [28]:
# GET RESULTS - NOW THAT THE MODEL HAS BEEN FITTED; LET SEE IF IT WORKS!
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


THE RETURN VALUE SHOULD BE R2

In [29]:
# Linear Regression
model.fit(x, y)
LinearRegression()

LinearRegression()

In [30]:
# Test Linear Regression
model = LinearRegression().fit(x, y)

In [31]:
# Test Linear Regression
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [32]:
# Test Linear Regression
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [33]:
# Test Linear Regression
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [34]:
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [35]:
# Test Linear Regression
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
# Test Linear Regression
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [37]:
# Test Linear Regression
y

array([ 5, 20, 14, 32, 22, 38])

In [38]:
# Test Linear Regression
model = LinearRegression().fit(x, y)

In [39]:
# Test Linear Regression
model = sm.OLS(y, x)

In [40]:
# Test Linear Regression
results = model.fit()

install conda install module_name

In [41]:
# Test Linear Regression
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.930
Model:                            OLS   Adj. R-squared (uncentered):              0.916
Method:                 Least Squares   F-statistic:                              66.71
Date:                Tue, 09 May 2023   Prob (F-statistic):                    0.000447
Time:                        21:22:47   Log-Likelihood:                         -19.692
No. Observations:                   6   AIC:                                      41.38
Df Residuals:                       5   BIC:                                      41.18
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/opt/homebrew/lib/python3.9/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [42]:
from statsmodels.compat import lzip
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [43]:
plt.rc("figure", figsize=(16, 8))
plt.rc("font", size=14)

In [44]:
prestige.head()

NameError: name 'prestige' is not defined

In [45]:
get_ipython().run_cell_magic('capture', '', "%logstop\n%logstart -t -r -q ipython_command_log.py global\n\n#- IRONHACKS RESEARCH TRACKING CODE\n#----------------------------------\n# The following code is used to help our research team understand how you \n# our notebook environment. We do not collect any personal information with\n# the following code, it is used to measure when and how often you work on\n# your submission files.\n\nimport os\nfrom datetime import datetime\nimport IPython.core.history as history\n\nha = history.HistoryAccessor()\nha_tail = ha.get_tail(1)\nha_cmd = next(ha_tail)\nsession_id = str(ha_cmd[0])\ncommand_id = str(ha_cmd[1])\ntimestamp = datetime.utcnow().isoformat()\nhistory_line = ','.join([session_id, command_id, timestamp]) + '\\n'\nlogfile = open(os.environ['HOME']+'/ipython_session_log.csv', 'a')\nlogfile.write(history_line)\nlogfile.close()\n")

SUBMISSION 11 Milestone
The task was to predict the total_claims for week 42
For each week there is a distinct list of uu_ids with unique uu_id in the table called prediction_list
Predict a value for each of those uu_ids
The list is changing over time (given the streaming nature of the data)

In [46]:
get_ipython().run_cell_magic('capture', '', "\n# INSTALL ADDITIONAL LIBRARIES IF REQUIRED\n# ------------------------------------------\n# This is normally not required. The hub environment comes preinstaled with \n# many packages that you can already use without setup. In case there is some\n# other library you would like to use that isn't on the list you run this command\n# once to install them.  If it is already installed this command has no effect.\n\n!python3 -m pip install pandas\n!python3 -m pip install [ensorflow]\n!python3 -m pip install [Keras]\n!python3 -m pip install [Pytorch]\n")

INSTALL PACKAGES

In [47]:
get_ipython().system('pip install db-dtypes')

IMPORT THE LIBRARIES YOU WILL USE
------------------------------------------
You only need to import packages one time per notebook session. To keep your
notebook clean and organized you can handle all imports at the top of your file.
The following are included for example purposed, feel free to modify or delete 
anything in this section.

In [48]:
import csv
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics
import statsmodels.api as sm
import math

IMPORT THE DATASET

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')

In [50]:
import os
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

IMPORT IRONHACKS DATA

In [51]:
import os
BIGQUERY_PROJECT = 'ironhacks-data'

In [52]:
bigquery.Client(project=BIGQUERY_PROJECT)

IMPORT THE LINEAR REGRESSION MODEL

In [53]:
import csv
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import matplotlib.pyplot as plt  

IMPORT PACKAGE THE LINEAR REGRESSION MODEL- SCIKIT-LEARN 
SOURCE: https://realpython.com/linear-regression-in-python/#simple-linear-regression-with-scikit-learn
NUMPY IS A FUNDAMENTAL PUYTHON SCIENTIFIC PACKAGE THAT ALLOWS MANY HIGH PEROFORMATION OPERATION SON A SINGLE AND MULTI DIMENSIONAL ARRAYS.
SOURCE: https://realpython.com/linear-regression-in-python/#python-packages-for-linear-regression

In [54]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [55]:
# DEFINING THE DATA; INPUTS (REGRESSOR.X) AND OUTPUTS (RESPONSE.Y)
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

DEFINE YOUR CLASSES AND FUNCTIONS 
-----------------------------------
This is not required, but is helpful in keeping your notebook organized. 
You can use the following cell or several cells to define your functions
and classes to keep them separate from your analysis or results code.
In general it useful to define your methods in a separate cell from where
it is run.

In [56]:
def example_function():
    print('Hello World')

In [57]:
# CREATE A LINEAR REGRESSION MODEL
model = LinearRegression()

START USING A MODEL - .fit() fits the model
SOURCE: REAL PYTHON - https://realpython.com/linear-regression-in-python/#simple-linear-regression-with-scikit-learn

In [58]:
model.fit(x,y)
LinearRegression

sklearn.linear_model._base.LinearRegression

In [59]:
# GET RESULTS - NOW THAT THE MODEL HAS BEEN FITTED; LET SEE IF IT WORKS!
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


THE RETURN VALUE SHOULD BE R2

DETERMIINE HOW TO GET b0 and b1 (scikit-learn)
intercept and coefficient are estimated values

In [60]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [61]:
# DETERMIINE HOW TO GET b0 and b1 (scikit-learn)
# intercept and coefficient are estimated values
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [62]:
# NOW THAT WE KNOW OUR MODEL IS WORKING; LET'S PREDICT A RESPONSE!
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


HERE'S ANOTHER WAY TO PREDICT THE RESPONSE
THIS IS WERE EACH ELEMENT OF X WERE MULTIPLIED BY WITH THE MODEL COEFFICIENT

In [63]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


REGRESSION MODELS ARE TYPCIALLY USED FOR FORECASTS
FITTED MODELS CAN BE USED TO CALCULATE THE OUTPUTS

In [64]:
x_new = np.arange(5). reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [65]:
# REGRESSION MODELS ARE TYPCIALLY USED FOR FORECASTS
# FITTED MODELS CAN BE USED TO CALCULATE THE OUTPUTS
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

Obtain data using BigQuery

In [66]:
BIGQUERY_PROJECT = 'ironhacks-data'
bigquery_client = bigquery.Client(project=BIGQUERY_PROJECT)

In [67]:
query = """
SELECT
x.*,
y.average_wage
FROM
(SELECT
*
FROM `ironhacks-data.ironhacks_competition.unemployment_data`) x
JOIN `ironhacks-data.ironhacks_competition.wage_data` y
ON x.uu_id = y.uu_id
"""

In [68]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()

In [69]:
query_pred = """
SELECT * FROM `ironhacks-data.ironhacks_competition.prediction_list`
"""

In [70]:
query_job_pred = bigquery_client.query(query_pred)
data_pred_query= query_job_pred.to_dataframe()

In [71]:
# START USING A MODEL - Same statement written differently
model = LinearRegression().fit(x,y)

In [72]:
# GET RESULTS - NOW THAT THE MODEL HAS BEEN FITTED; LET SEE IF IT WORKS!
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


THE RETURN VALUE SHOULD BE R2

In [73]:
# Linear Regression
model.fit(x, y)
LinearRegression()

LinearRegression()

In [74]:
# Test Linear Regression
model = LinearRegression().fit(x, y)

In [75]:
# Test Linear Regression
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [76]:
# Test Linear Regression
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [77]:
# Test Linear Regression
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")

intercept: [5.63333333]


In [78]:
print(f"slope: {new_model.coef_}")

slope: [[0.54]]


In [79]:
# Test Linear Regression
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [80]:
# Test Linear Regression
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [81]:
# Test Linear Regression
y

array([ 5, 20, 14, 32, 22, 38])

In [82]:
# Test Linear Regression
model = LinearRegression().fit(x, y)

In [83]:
# Test Linear Regression
model = sm.OLS(y, x)

In [84]:
# Test Linear Regression
results = model.fit()

install conda install module_name

In [85]:
# Test Linear Regression
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.930
Model:                            OLS   Adj. R-squared (uncentered):              0.916
Method:                 Least Squares   F-statistic:                              66.71
Date:                Tue, 09 May 2023   Prob (F-statistic):                    0.000447
Time:                        21:22:55   Log-Likelihood:                         -19.692
No. Observations:                   6   AIC:                                      41.38
Df Residuals:                       5   BIC:                                      41.18
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/opt/homebrew/lib/python3.9/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [86]:
from statsmodels.compat import lzip
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [87]:
plt.rc("figure", figsize=(16, 8))
plt.rc("font", size=14)

In [88]:
prestige.head()

NameError: name 'prestige' is not defined

In [89]:
from statsmodels.compat import lzip
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [90]:
plt.rc("figure", figsize=(16, 8))
plt.rc("font", size=14)

In [91]:
prestige.head()

NameError: name 'prestige' is not defined

In [92]:
prestige_model = ols("prestige ~ income + education", data=prestige).fit()

NameError: name 'prestige' is not defined

In [93]:
prestige.head()

NameError: name 'prestige' is not defined

In [94]:
prestige.head()

NameError: name 'prestige' is not defined

In [95]:
from statsmodels.compat import lzip
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [96]:
plt.rc("figure", figsize=(16, 8))
plt.rc("font", size=14)

In [97]:
dta = sm.datasets.statecrime.load_pandas().data

In [98]:
prestige.head()

NameError: name 'prestige' is not defined

In [99]:
print(prestige_model.summary())

NameError: name 'prestige_model' is not defined

In [100]:
dta = sm.datasets.statecrime.load_pandas().data

In [101]:
crime_model = ols("claim ~ uu_id + tract + age + single", data=dta).fit()
print(crime_model.summary())

PatsyError: Error evaluating factor: NameError: name 'age' is not defined
    claim ~ uu_id + tract + age + single
                            ^^^

In [102]:
crime_model = ols("murder ~ urban + poverty + hs_grad + single", data=dta).fit()
print(crime_model.summary())

                            OLS Regression Results                            
Dep. Variable:                 murder   R-squared:                       0.813
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                     50.08
Date:                Tue, 09 May 2023   Prob (F-statistic):           3.42e-16
Time:                        21:22:55   Log-Likelihood:                -95.050
No. Observations:                  51   AIC:                             200.1
Df Residuals:                      46   BIC:                             209.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -44.1024     12.086     -3.649      0.0

In [103]:
prestige.head()

NameError: name 'prestige' is not defined

In [104]:
prestige_model = ols("prestige ~ income + education", data=prestige).fit()

NameError: name 'prestige' is not defined

In [105]:
print(prestige_model.summary())

NameError: name 'prestige_model' is not defined